CREATE TABLE UserOwnedGames
	(
		UserId UNIQUEIDENTIFIER NOT NULL,
		GameId UNIQUEIDENTIFIER NOT NULL,
		PurchaseDate DATETIMEOFFSET DEFAULT SYSDATETIMEOFFSET(),
		CONSTRAINT FK_UserOwnedGames_UserId FOREIGN KEY (UserId) REFERENCES Users(UserId) ON DELETE CASCADE,
		CONSTRAINT FK_UserOwnedGames_GameId FOREIGN KEY (GameId) REFERENCES Games(GameId),
		CONSTRAINT UC_UserOwnedGames UNIQUE (UserId, GameId)
	);