CREATE OR ALTER PROC usp_DeleteGameById
@GameId UNIQUEIDENTIFIER
AS
BEGIN
	IF NOT EXISTS(SELECT 1 FROM Games WHERE GameId = @GameId)
	BEGIN
		RAISERROR('The game that you want to delete does not exist!', 16, 1);
		RETURN;
	END
	BEGIN TRANSACTION
	BEGIN TRY
		DELETE FROM Games WHERE GameId = @GameId;
		COMMIT TRANSACTION
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0
			ROLLBACK TRANSACTION;
		THROW;
	END CATCH
END;