IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='Users')
BEGIN
    CREATE TABLE Users
    (
        id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
        username VARCHAR(25) NOT NULL UNIQUE,
        email VARCHAR(100) NOT NULL UNIQUE,
        password VARCHAR(255) NOT NULL
    );
END;